import "server-only";
// Mock CompetitorDirectory: ten nearby rivals, deterministic, spread from clearly ahead to clearly behind.
import type { Competitor, CompetitorDirectory } from "./types";

type Rival = Omit<Competitor, "source" | "fetchedAt" | "keywordPositions"> & {
  /** Offset added to their average position per keyword, so each keyword ranks a little differently. */
  spread: readonly number[];
};

const rivals: readonly Rival[] = [
  {
    name: "Luxe Hair Studio",
    websiteUrl: "https://luxehairstudio.example",
    averageRating: 4.8,
    reviewCount: 214,
    reviewsLast30Days: 17,
    reviewsPrevious30Days: 11,
    averageMapPosition: 1.6,
    services: ["Haircut", "Balayage", "Hair Colour", "Keratin Treatment", "Hair Extensions", "Bridal Makeup"],
    pageTopics: [
      "Haircut",
      "Balayage",
      "Hair Colour",
      "Keratin Treatment",
      "Hair Extensions",
      "Bridal Makeup",
      "Pricing",
      "Gallery",
      "FAQ",
      "Book Online",
    ],
    totalPages: 28,
    postsLast90Days: 14,
    photoCount: 96,
    spread: [0, 1, -1, 0, 1, 0],
  },
  {
    name: "Glow Beauty Lounge",
    websiteUrl: "https://glowbeautylounge.example",
    averageRating: 4.6,
    reviewCount: 187,
    reviewsLast30Days: 12,
    reviewsPrevious30Days: 9,
    averageMapPosition: 2.4,
    services: ["Haircut", "Balayage", "Facials", "Waxing", "Bridal Makeup"],
    pageTopics: ["Haircut", "Balayage", "Facials", "Bridal Makeup", "Pricing", "Gallery", "Book Online"],
    totalPages: 22,
    postsLast90Days: 9,
    photoCount: 71,
    spread: [1, 0, 1, -1, 0, 2],
  },
  {
    name: "The Colour Bar",
    websiteUrl: "https://thecolourbar.example",
    averageRating: 4.7,
    reviewCount: 142,
    reviewsLast30Days: 9,
    reviewsPrevious30Days: 10,
    averageMapPosition: 3.1,
    services: ["Hair Colour", "Balayage", "Highlights", "Haircut"],
    pageTopics: ["Hair Colour", "Balayage", "Highlights", "Haircut", "Colour Correction", "FAQ"],
    totalPages: 18,
    postsLast90Days: 11,
    photoCount: 64,
    spread: [2, -1, 0, 1, 2, 0],
  },
  {
    name: "Bridal Glam Co.",
    websiteUrl: "https://bridalglam.example",
    averageRating: 4.9,
    reviewCount: 121,
    reviewsLast30Days: 8,
    reviewsPrevious30Days: 5,
    averageMapPosition: 3.8,
    services: ["Bridal Makeup", "Hair Styling", "Threading"],
    pageTopics: ["Bridal Makeup", "Bridal Hair", "Packages", "Gallery", "Testimonials"],
    totalPages: 15,
    postsLast90Days: 16,
    photoCount: 132,
    spread: [3, 2, 1, -2, 3, 2],
  },
  {
    name: "Urban Cuts Salon",
    websiteUrl: "https://urbancuts.example",
    averageRating: 4.5,
    reviewCount: 168,
    reviewsLast30Days: 7,
    reviewsPrevious30Days: 8,
    averageMapPosition: 4.2,
    services: ["Haircut", "Beard Trim", "Hair Colour"],
    pageTopics: ["Haircut", "Men's Cuts", "Hair Colour", "Pricing"],
    totalPages: 11,
    postsLast90Days: 4,
    photoCount: 38,
    spread: [-1, 1, 2, 3, 1, 0],
  },
  {
    name: "Silk & Shine Hair",
    websiteUrl: "https://silkandshine.example",
    averageRating: 4.6,
    reviewCount: 98,
    reviewsLast30Days: 6,
    reviewsPrevious30Days: 3,
    averageMapPosition: 5.0,
    services: ["Keratin Treatment", "Hair Extensions", "Haircut", "Hair Colour"],
    pageTopics: ["Keratin Treatment", "Hair Extensions", "Haircut", "FAQ", "Aftercare"],
    totalPages: 14,
    postsLast90Days: 6,
    photoCount: 45,
    spread: [1, 2, 0, 2, -2, 1],
  },
  {
    name: "Maple Beauty Bar",
    websiteUrl: null,
    averageRating: 4.3,
    reviewCount: 76,
    reviewsLast30Days: 3,
    reviewsPrevious30Days: 4,
    averageMapPosition: 6.4,
    services: ["Threading", "Waxing", "Facials"],
    pageTopics: [],
    totalPages: 0,
    postsLast90Days: 2,
    photoCount: 22,
    spread: [2, 3, 1, 0, 2, 3],
  },
  {
    name: "Studio Nine Hair",
    websiteUrl: "https://studionine.example",
    averageRating: 4.4,
    reviewCount: 64,
    reviewsLast30Days: 4,
    reviewsPrevious30Days: 4,
    averageMapPosition: 7.2,
    services: ["Haircut", "Balayage", "Highlights"],
    pageTopics: ["Haircut", "Balayage", "Pricing"],
    totalPages: 8,
    postsLast90Days: 3,
    photoCount: 29,
    spread: [0, 2, 3, 1, 1, 2],
  },
  {
    name: "Serenity Salon & Spa",
    websiteUrl: "https://serenitysalonspa.example",
    averageRating: 4.2,
    reviewCount: 58,
    reviewsLast30Days: 2,
    reviewsPrevious30Days: 3,
    averageMapPosition: 8.5,
    services: ["Facials", "Massage", "Haircut", "Waxing"],
    pageTopics: ["Facials", "Massage", "Haircut", "Spa Packages", "Gift Cards"],
    totalPages: 16,
    postsLast90Days: 5,
    photoCount: 51,
    spread: [3, 1, 2, 2, 0, 1],
  },
  {
    name: "Chic Hair Collective",
    websiteUrl: "https://chichair.example",
    averageRating: 4.1,
    reviewCount: 41,
    reviewsLast30Days: 1,
    reviewsPrevious30Days: 2,
    averageMapPosition: 9.6,
    services: ["Haircut", "Hair Colour", "Hair Extensions"],
    pageTopics: ["Haircut", "Hair Colour", "Hair Extensions"],
    totalPages: 7,
    postsLast90Days: 1,
    photoCount: 18,
    spread: [1, 0, 2, 3, 2, 1],
  },
];

export class MockCompetitorDirectory implements CompetitorDirectory {
  async findNearby({ keywords, limit }: { keywords: readonly string[]; limit: number }): Promise<Competitor[]> {
    const fetchedAt = new Date();
    return rivals.slice(0, limit).map(({ spread, ...rival }) => ({
      ...rival,
      keywordPositions: keywords.map((keyword, index) => {
        const position = Math.round(rival.averageMapPosition + (spread[index % spread.length] ?? 0));
        // Past the map pack's usual depth they simply do not show.
        return { keyword, mapPosition: position >= 1 && position <= 20 ? position : null };
      }),
      source: "mock",
      fetchedAt,
    }));
  }
}
