// Salon pack (MVP 2): page and post types.
import type { VerticalContentType } from "@/shared/types/vertical";

export const contentTypes: readonly VerticalContentType[] = [
  {
    id: "service-page",
    channel: "website",
    name: "Service Page",
    description: "Generate SEO-optimized service pages",
    icon: "page",
    estimatedMinutes: 4,
  },
  {
    id: "location-page",
    channel: "website",
    name: "Location Page",
    description: "Create location-specific pages",
    icon: "location",
    estimatedMinutes: 4,
  },
  {
    id: "faqs",
    channel: "website",
    name: "FAQs",
    description: "Answer common customer questions",
    icon: "faq",
    estimatedMinutes: 2,
  },
  {
    id: "before-after",
    channel: "website",
    name: "Before/After Descriptions",
    description: "Write compelling transformation stories",
    icon: "compare",
    estimatedMinutes: 2,
  },
  {
    id: "staff-profiles",
    channel: "website",
    name: "Stylist Profiles",
    description: "Create professional team bios",
    icon: "person",
    estimatedMinutes: 3,
  },
  {
    id: "pricing-explainer",
    channel: "website",
    name: "Pricing Explanations",
    description: "Explain your services and pricing clearly",
    icon: "price",
    estimatedMinutes: 3,
  },
  {
    id: "treatment-guide",
    channel: "website",
    name: "Treatment Guides",
    description: "Educational content for your clients",
    icon: "guide",
    estimatedMinutes: 6,
  },
  {
    id: "blog-article",
    channel: "website",
    name: "Blog Articles",
    description: "Salon tips, trends and seasonal content",
    icon: "article",
    estimatedMinutes: 8,
  },
  {
    id: "google-post",
    channel: "google",
    name: "Google Post",
    description: "Short updates that keep your listing active",
    icon: "megaphone",
    estimatedMinutes: 1,
  },
  {
    id: "google-offer",
    channel: "google",
    name: "Offer Post",
    description: "Promote a seasonal offer with an end date",
    icon: "tag",
    estimatedMinutes: 2,
  },
  {
    id: "google-qa",
    channel: "google",
    name: "Questions & Answers",
    description: "Seed the questions customers actually ask",
    icon: "faq",
    estimatedMinutes: 2,
  },
  {
    id: "review-reply",
    channel: "google",
    name: "Review Replies",
    description: "On-brand replies to every review",
    icon: "reply",
    estimatedMinutes: 1,
  },
  {
    id: "instagram-caption",
    channel: "social",
    name: "Instagram Caption",
    description: "Captions with the hashtags that work locally",
    icon: "camera",
    estimatedMinutes: 1,
  },
  {
    id: "reel-script",
    channel: "social",
    name: "Reel Script",
    description: "A 30-second script your team can film today",
    icon: "video",
    estimatedMinutes: 3,
  },
  {
    id: "facebook-post",
    channel: "social",
    name: "Facebook Post",
    description: "Longer posts for your local community",
    icon: "megaphone",
    estimatedMinutes: 2,
  },
  {
    id: "story-series",
    channel: "social",
    name: "Story Series",
    description: "A five-frame story that ends in a booking",
    icon: "layers",
    estimatedMinutes: 4,
  },
  {
    id: "rebooking-email",
    channel: "email",
    name: "Rebooking Reminder",
    description: "Bring clients back before they drift",
    icon: "mail",
    estimatedMinutes: 2,
  },
  {
    id: "welcome-email",
    channel: "email",
    name: "Welcome Sequence",
    description: "Three emails for a brand new client",
    icon: "mail",
    estimatedMinutes: 5,
  },
  {
    id: "winback-email",
    channel: "email",
    name: "Win-back Email",
    description: "Reach clients who have not been in for months",
    icon: "mail",
    estimatedMinutes: 3,
  },
  {
    id: "newsletter",
    channel: "email",
    name: "Monthly Newsletter",
    description: "One send that covers offers, tips and news",
    icon: "article",
    estimatedMinutes: 6,
  },
];
